USE [master]
GO
/****** Object:  Database [schoolBD]    Script Date: 18.09.2022 14:52:17 ******/
CREATE DATABASE [schoolBD]
 CONTAINMENT = NONE
-- ON  PRIMARY 
--( NAME = N'schoolBD', FILENAME = N'C:\Users\Костя\schoolBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
-- LOG ON 
--( NAME = N'schoolBD_log', FILENAME = N'C:\Users\Костя\schoolBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [schoolBD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [schoolBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [schoolBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [schoolBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [schoolBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [schoolBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [schoolBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [schoolBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [schoolBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [schoolBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [schoolBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [schoolBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [schoolBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [schoolBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [schoolBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [schoolBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [schoolBD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [schoolBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [schoolBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [schoolBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [schoolBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [schoolBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [schoolBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [schoolBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [schoolBD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [schoolBD] SET  MULTI_USER 
GO
ALTER DATABASE [schoolBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [schoolBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [schoolBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [schoolBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [schoolBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [schoolBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [schoolBD] SET QUERY_STORE = OFF
GO
USE [schoolBD]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Country] [varchar](50) NOT NULL,
	[City] [varchar](50) NOT NULL,
	[Street] [varchar](50) NOT NULL,
	[PostalCode] [int] NOT NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Director]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Director](
	[ID] [int] NOT NULL,
 CONSTRAINT [PK_Director] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[SecondName] [varchar](50) NOT NULL,
	[Age] [int] NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Floor]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Floor](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[SchoolID] [int] NOT NULL,
 CONSTRAINT [PK_Floor] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Room]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Number] [int] NOT NULL,
	[FloorID] [int] NOT NULL,
	[RoomTypeID] [int] NOT NULL,
 CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RoomType]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RoomType](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_RoomType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[School]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[School](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[AddressID] [int] NOT NULL,
	[OpeningDate] [date] NULL,
 CONSTRAINT [PK_School] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SchoolEmployee]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SchoolEmployee](
	[EmployeeID] [int] NOT NULL,
	[SchoolID] [int] NOT NULL,
 CONSTRAINT [PK_SchoolEmployee] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC,
	[SchoolID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Teacher]    Script Date: 18.09.2022 14:52:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Teacher](
	[ID] [int] NOT NULL,
 CONSTRAINT [PK_Teacher] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Director]  WITH CHECK ADD  CONSTRAINT [FK_Director_Employee] FOREIGN KEY([ID])
REFERENCES [dbo].[Employee] ([ID])
GO
ALTER TABLE [dbo].[Director] CHECK CONSTRAINT [FK_Director_Employee]
GO
ALTER TABLE [dbo].[Floor]  WITH NOCHECK ADD  CONSTRAINT [FK_Floor_School] FOREIGN KEY([SchoolID])
REFERENCES [dbo].[School] ([ID])
GO
ALTER TABLE [dbo].[Floor] CHECK CONSTRAINT [FK_Floor_School]
GO
ALTER TABLE [dbo].[Room]  WITH CHECK ADD  CONSTRAINT [FK_Room_Room] FOREIGN KEY([RoomTypeID])
REFERENCES [dbo].[RoomType] ([ID])
GO
ALTER TABLE [dbo].[Room] CHECK CONSTRAINT [FK_Room_Room]
GO
ALTER TABLE [dbo].[School]  WITH CHECK ADD  CONSTRAINT [FK_School_Address] FOREIGN KEY([AddressID])
REFERENCES [dbo].[Address] ([ID])
GO
ALTER TABLE [dbo].[School] CHECK CONSTRAINT [FK_School_Address]
GO
ALTER TABLE [dbo].[SchoolEmployee]  WITH CHECK ADD  CONSTRAINT [FK_SchoolEmployee_Employee] FOREIGN KEY([SchoolID])
REFERENCES [dbo].[School] ([ID])
GO
ALTER TABLE [dbo].[SchoolEmployee] CHECK CONSTRAINT [FK_SchoolEmployee_Employee]
GO
ALTER TABLE [dbo].[Teacher]  WITH CHECK ADD  CONSTRAINT [FK_Teacher_Employee] FOREIGN KEY([ID])
REFERENCES [dbo].[Employee] ([ID])
GO
ALTER TABLE [dbo].[Teacher] CHECK CONSTRAINT [FK_Teacher_Employee]
GO
USE [master]
GO
ALTER DATABASE [schoolBD] SET  READ_WRITE 
GO
